// vue-front/src/components/Header.vue
<script setup lang="ts">
import { useRouter } from 'vue-router'; // 리액트의 useNavigate 역할
import type { Menu } from '../menu';
import '../css/layout.css';
// Props 정의
const props = defineProps<{
  mainMenus: Menu[];
  activeMenu: Menu;
}>();

// Emit 정의 (부모의 setActiveMenu 호출 역할)
const emit = defineEmits<{
  (e: 'setActiveMenu', menu: Menu): void;
}>();

const router = useRouter(); // "페이지 이동 리모컨" 생성

const topMenuClick = (menu: Menu) => {
  // 1. 활성 메뉴 상태 변경 요청
  emit('setActiveMenu', menu);
  
};
</script>

<template>
  <div id="header">
    <div class="header-left">
      <div class="logo-area">
        <span class="logo-icon">💚</span>
        <span class="logo-text">Vue Study</span>
      </div>
    </div>
    <div class="header-center">
      <div class="header-menu">
        <div
          v-for="menu in mainMenus"
          :key="menu.menuId"
          class="menu-item"
          :class="{ active: activeMenu.menuId === menu.menuId }"
          @click="topMenuClick(menu)"
        >
          {{ menu.menuName }}
        </div>
      </div>
    </div>
  </div>
</template>

// react-front/src/assets/Header.tsx
interface Menu {
  menuId: string;
  menuName: string;
}

interface Props {
  menus: Menu[];
  activeMenu: string;
  setActiveMenu: (id: string) => void;
}

function Header({ menus, activeMenu, setActiveMenu }: Props) {

  return (
    <div id="header">

      <div className="header-left">
        <div className="logo-area">
          <span className="logo-icon">⚛️</span>
          <span className="logo-text">React Study</span>
        </div>
      </div>

      <div className="header-center">
        <div className="header-menu">
          {menus.map(menu => (
            <div
              key={menu.menuId}
              className={`menu-item ${
                activeMenu === menu.menuId ? "active" : ""
              }`}
              onClick={() => setActiveMenu(menu.menuId)}
            >
              {menu.menuName}
            </div>
          ))}
        </div>
      </div>

      <div className="header-right">
        <span className="user-icon">👤</span>
        <span className="user-name">Developer</span>
      </div>

    </div>
  );
}

export default Header;
