// react-front/src/pages/UserManagement.tsx
import { type Menu } from "../menu";

// App.tsx에서 전달하는 Props와 타입을 일치시킵니다.
interface UserManagementProps {
  level2Menus: Menu[];
  activeLevel2: Menu | null;
  onSelect: (menu: Menu | null) => void;
}

export default function UserManagement({
  level2Menus,
  activeLevel2,
  onSelect: _onSelect, // 변수명 앞에 _ 추가
}: UserManagementProps) {
  const currentMenuName = activeLevel2?.menuName || "User Management";

  return (
    <div className="user-mgmt-page">
      <div className="user-mgmt-card">
        <div className="user-mgmt-icon">👤</div>
        <h1>{currentMenuName}</h1>
        <p className="status-text">현재 개발중입니다</p>
        <p className="sub-text">곧 기능이 추가됩니다</p>
      </div>

      {/* 디자인 일관성을 위해 하단에 메뉴 목록을 표시하거나 로직을 추가할 수 있습니다 */}
      {level2Menus.length > 0 && (
        <div style={{ marginTop: "20px", fontSize: "14px", color: "#666" }}>
          관리 가능 메뉴: {level2Menus.map((m) => m.menuName).join(", ")}
        </div>
      )}
    </div>
  );
}

// vue-front/src/pages/UserManagement.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { Menu } from '../menu';

// 1. Props 정의
interface UserManagementProps {
  level2Menus: Menu[];
  activeLevel2: Menu | null;
}

const props = defineProps<UserManagementProps>();

// 2. Emit 정의 (부모의 onSelect 역할)
const emit = defineEmits<{
  (e: 'onSelect', menu: Menu | null): void;
}>();

// 3. Computed 속성 (리액트의 변수 계산 로직 역할)
const currentMenuName = computed(() => {
  return props.activeLevel2?.menuName || "User Management";
});

// 관리 가능한 메뉴 이름을 쉼표로 연결
const manageableMenus = computed(() => {
  return props.level2Menus.map((m) => m.menuName).join(", ");
});
</script>

<template>
  <div class="user-mgmt-page">
    <div class="user-mgmt-card">
      <div class="user-mgmt-icon">👤</div>
      <h1>{{ currentMenuName }}</h1>
      <p class="status-text">현재 개발중입니다</p>
      <p class="sub-text">곧 기능이 추가됩니다</p>
    </div>

    <!-- 4. 조건부 렌더링 (v-if) -->
    <div 
      v-if="level2Menus.length > 0" 
      class="manageable-list"
    >
      관리 가능 메뉴: {{ manageableMenus }}
    </div>
  </div>
</template>

<style scoped>
/* 페이지 전용 스타일 */
.user-mgmt-page {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 40px;
}

.user-mgmt-card {
  background: white;
  padding: 40px;
  border-radius: 16px;
  text-align: center;
  box-shadow: 0 4px 12px rgba(0,0,0,0.08);
  width: 100%;
  max-width: 500px;
}

.user-mgmt-icon {
  font-size: 60px;
  margin-bottom: 20px;
}

.status-text {
  color: #ef4444;
  font-weight: bold;
  margin-top: 15px;
}

.sub-text {
  color: #64748b;
  font-size: 14px;
}

.manageable-list {
  margin-top: 20px;
  font-size: 14px;
  color: #666;
}
</style>
