// react-front/src/pages/WbsSetup.tsx
//React  핵심 훅(Hooks)
import { useEffect, useState, useRef, useMemo, useCallback } from "react";
//AgGridReact 컴포넌트
/* AgGridReact 기본 설정 및 사용법 : rowData(데이터)와 columnDefs(컬럼 정의)가 필수

import { AgGridReact } from "ag-grid-react";
import "ag-grid-community/styles/ag-grid.css"; // 핵심 그리드 CSS
import "ag-grid-community/styles/ag-theme-alpine.css"; // 테마 CSS

const MyGrid = () => {
	
  // 13. API 접근을 위한 Ref
  const gridRef = useRef(null);
	
  // 2. 데이터 (useState로 관리 권장)
  const [rowData, setRowData] = useState([
    { id: 1, make: "Toyota", model: "Celica", price: 35000 },
    { id: 2, make: "Ford", model: "Mondeo", price: 32000 },
  ]);

  // 3. 컬럼 정의 (useMemo로 최적화 권장) : columnDefs는 useMemo를 사용하여 컴포넌트가 리렌더링될 때마다 배열이 새로 생성되지 않도록 함
  const columnDefs = useMemo(() => [
    { field: "make", sortable: true, filter: true },
    { field: "model" },
    { field: "price", editable: true }
  ], []);

  // 4. 기본 컬럼 설정: 공통 옵션 적용
  const defaultColDef = useMemo(() => ({
    flex: 1,
    filter: true,
    floatingFilter: true,
  }), []);

  // 5. 데이터 로드 (useEffect 활용)
  useEffect(() => {
    fetch("https://www.ag-grid.com")
      .then(res => res.json())
      .then(data => setRowData(data));
  }, []);
  
  // 6. 셀 클릭 이벤트 예시 (useCallback 활용) useCallback은 **함수 자체를 메모리에 저장(Memoization)**하여, 컴포넌트가 리렌더링될 때마다 함수가 새로 생성되는 것을 방지하는 Hook
  const onCellClicked = useCallback((params) => {
    console.log("Cell Clicked:", params.data);
  }, []);
  
  return (
    // 그리드 컨테이너의 높이가 반드시 지정되어야 함
    <div className="ag-theme-alpine" style={{ height: 400, width: '100%' }}>
      <AgGridReact
        ref={gridRef}
        rowData={rowData}
        columnDefs={columnDefs}
		defaultColDef={defaultColDef}
		rowSelection="multiple"
		onCellClicked={onCellClicked}
        animateRows={true} // 행 애니메이션 활성화
        pagination={true} // 페이지네이션 활성화
      />
    </div>
  );
};

*/
// AG Grid 라이브러리 ag-grid-community와 ag-grid-react의 버전은 항상 동일하게 유지
import { AgGridReact } from "ag-grid-react";
//Enterprise 기능을 사용, 필요한 모듈만 골라서 등록 하기 위해
import { ModuleRegistry } from "ag-grid-community";
//AG Grid v31.x 버전 이상의 모듈형 방식
import {
		RenderApiModule ,
        DateEditorModule, 
		ClientSideRowModelModule,
        ValidationModule,   // 데이터 편집 시 유효성 검사 로직을 활성화할 때 필요.
        CellStyleModule,
        TextEditorModule,
        NumberEditorModule,
		ScrollApiModule,    //특정 행으로 스크롤하거나
		RowApiModule,       // 행 위치를 계산하는 복잡한 API 기능을 사용 ex : gridRef.current.api.getRowNode(id)
		RowSelectionModule, // <--- 체크박스 선택 기능을 위해 함께 추가 권장
		themeQuartz        // 테마 객체 : AgGridReact의 theme props에 직접 전달하여 사용
} from "ag-grid-community";

//TypeScript 타입 명시
/*
// 1. ColDef 타입을 사용하여 컬럼 정의의 자동완성과 오타 방지
interface IData {
  id: number;
  name: string;
  age: number;
}
// ColDef<IData>: field 속성을 적을 때 IData 인터페이스에 정의된 키값만 들어오도록 강력하게 제한
const columnDefs = useMemo<ColDef<IData>[]>(() => [
  { field: "id", headerName: "ID", width: 70 },
  { field: "name", editable: true },
  { field: "age", editable: true, cellEditor: "agNumberCellEditor" }
], []);

// 2. CellValueChangedEvent 타입을 사용해 편집 이벤트 핸들러 작성
const onCellValueChanged = useCallback((event: CellValueChangedEvent<IData>) => {
  const { data, newValue, oldValue, column } = event;
  console.log(`${column.getColId()} 값이 변경됨: ${oldValue} -> ${newValue}`);
  // 여기서 서버 저장 API 등을 호출할 수 있습니다.
}, []);

// 3. GridApi를 직접 다룰 때의 타입 지정 예시
const getSelectedRows = () => {
  const api: GridApi<IData> | undefined = gridRef.current?.api;
  if (api) {
    const selectedData = api.getSelectedRows();
    console.log("선택된 데이터:", selectedData);
  }
};
*/
import type { GridApi, ColDef, CellValueChangedEvent } from "ag-grid-community";

// 1. 모듈 등록 (컴포넌트 외부에서 한 번만 실행) (themeQuartz는 모듈이 아니므로 여기서 제외)
ModuleRegistry.registerModules([
  ScrollApiModule,
  RenderApiModule ,
  DateEditorModule, 
  ClientSideRowModelModule,
  RowApiModule,
  RowSelectionModule,
  ValidationModule,
  CellStyleModule,
  TextEditorModule,
  NumberEditorModule,
]);


interface SearchParams {
  activityName?: string;
  outputName?: string;
  startDate?: string;
  endDate?: string;
}

interface SelectBoxData {
  activityName: string;
  outputName: string;
}

interface RowData {
  activityId: string;
  activityDate: string;
  activityName: string;
  outputName: string;
  targetQty: number;
  // |는 유니온 타입(Union Type)을 정의하는 구분자 , 
  // 이 변수는 A 또는 B 또는 C 중 하나의 값만 가질 수 있다"는 뜻의 'OR(또는)' 연산자 역할
  _rowState: "NORMAL" | "INSERT" | "UPDATE";
  // Record<string, boolean> : TypeScript에서 **"키(Key)는 문자열(string)이고, 값(Value)은 불리언(boolean)인 객체"**를 정의하는 타입 도구
  // ?가 붙은 것은 이 필드가 **옵션(Optional)**임을 뜻하며, 데이터가 없을 수도 있다는 의미
  //  부분 업데이트(Partial Update): 서버에 데이터를 저장할 때, 행 전체를 보내는 대신 _editedFields에 true로 체크된 컬럼만 골라서 보낼 수 있어 네트워크 비용을 아낍니다.
  //  시각적 피드백: 그리드의 cellStyle 설정에서 params.data._editedFields?.[params.colDef.field]가 true인 셀에만 노란색 배경을 칠해주는 식으로 "수정된 셀 강조" 기능을 쉽게 구현합니다.
  //  유연성: Record<string, boolean>은 키 이름을 미리 정해두지 않기 때문에, 나중에 새로운 컬럼(activityDate 등)이 추가되어도 코드를 수정할 필요 없이 바로 대응이 가능합니다.
  _editedFields?: Record<string, boolean>;
  _oldValues?: {
	activityDate: string;
	activityName: string;
	outputName: string;
	targetQty: number;
  };
}

function WbsSetup() {
	// useRef (보관함) : React에서 컴포넌트가 리렌더링되어도 값이 초기화되지 않고 유지되는 저장 공간
	// <GridApi<RowData> | null>  "AG Grid를 내 마음대로 조종할 수 있는 도구 모음 <RowData>를 붙여줌으로써 API가 내뱉는 데이터가 우리가 정의한 인터페이스 형태임을 보장
	//| null: 처음에 화면이 그려지기 전에는 API가 아직 생성되지 않았으므로 "비어 있을 수 있음"을 명시
	// (null);는 useRef를 선언할 때 초기값을 비워두겠다는 의미입니다.
	// 나중에 onGridReady 속성을 통해 실제 값을 채워
    /*
	<AgGridReact
	  // 그리드가 준비 완료되면 실행되는 함수
	  onGridReady={(params) => {
	    // 이제 null이었던 보관함에 진짜 API 리모컨이 들어갑니다.
	    gridApiRef.current = params.api;
	  }}
	/>
	params 정보 : 1. api : 그리드를 프로그램적으로 제어하는 수백 개의 메서드가 담겨 있음
	                      params.api.setGridOption(): 그리드 설정 동적 변경
	                      params.api.applyTransaction(): 데이터 추가/삭제/수정
	                      params.api.getSelectedRows(): 선택된 데이터 가져오기
	                      params.api.refreshCells(): 특정 셀만 다시 그리기
				2. context: 전역 데이터 공유 객체	  
				3. 기타 메타데이터 : type: 이벤트 이름 (여기선 "gridReady"), source: 이벤트가 발생한 원인
	*/
  const gridApiRef = useRef<GridApi<RowData> | null>(null);
  
  //삭제한 행들을 서버에 최종 전송하기 전까지 임시로 담아두는 '장바구니'
  //왜 useState가 아닌 useRef인가 : 사용자가 행을 삭제할 때마다 화면을 다시 그릴(리렌더링) 필요가 없음
  const deletedRowsRef = useRef<RowData[]>([]);

  //[string, string]: 딱 두 개의 문자열만 들어갈 수 있는 고정된 배열(튜플)
  //ex : ["activityName", "설계"] 같은 형태. 보통 [필터컬럼명, 필터값]으로 매칭
  // []: 위에서 말한 튜플들이 여러 개 모인 배열
  // 일반적인 객체({ field: value }) 대신 이 형태를 쓰는이유
  // 순서 보장, 지도(Map) 변환 용이, API 호출 시 ?activityName=설계&outputName=도면 처럼 파라미터를 동적으로 만들 때 반복문(forEach)을 돌리기 매우 편한 구조
  const [filterData, setFilterData] = useState<[string, string][]>([]); 
  const [activities, setActivities] = useState<[string, string][]>([]);
  const [outputs, setOutputs] = useState<[string, string][]>([]);
  
  const [activityName, setActivityName] = useState("");
  const [outputName, setOutputName] = useState("");

  const [showSearch, setShowSearch] = useState(true);
  const [rowData, setRowData] = useState<RowData[]>([]);

  const [startDate,setStartDate] = useState("");
  const [endDate,setEndDate] = useState("");
  
  /*
  useMemo, useRef 차이점과 공통점 
  리렌더링이 발생해도 값을 유지한다는 공통점
  useMemo: 복잡한 계산 결과(값)를 재사용하여 성능을 높일 때 (성능 최적화용)
  useRef: 값이 변해도 화면을 다시 그리지 않고 데이터만 저장하거나 DOM에 접근할 때 (저장소/리모컨용)
  */
  //기본 컬럼 정의
  const defaultColDef = useMemo<ColDef>(() => ({
    resizable: true,
    sortable: true,
    flex: 1,
    minWidth: 100
  }), []);
  
  /* =========================
     Columns
     ========================= */
	 //AgGridReact 속성 columnDefs 정의
	 //ColDef<RowData>[] : TypeScript 타입 지정 
	 //ColDef: AG Grid가 제공하는 타입으로, 컬럼 설정에 쓸 수 있는 속성(예: field, headerName, editable 등)만 사용하도록 제한.
	 const columnDefs: ColDef<RowData>[] = useMemo(() => [
	   {
	     headerName: 'No',
	     valueGetter: "node.rowIndex + 1",
	     width: 60,
		 minWidth: 60,   // 최소 너비 제한을 풀어줌 (중요!)
		 maxWidth: 70,   // 너무 커지는 걸 방지하려면 추가
	     pinned: 'left',
	     cellStyle: () => ({ textAlign: 'center', color: '#888' }), 
	   }, 
	   { 
	     headerName: 'Sel', 
	     width: 60,
		 minWidth: 60,   // 최소 너비 제한을 풀어줌 (중요!)
		 maxWidth: 70,   // 너무 커지는 걸 방지하려면 추가
	     checkboxSelection: true, 
	     headerCheckboxSelection: true,
	     pinned: 'left',
	     cellStyle: () => ({ display: 'flex', justifyContent: 'center' }),
	     headerClass: 'ag-header-cell-center', 
	   }, 
	   { 
	     headerName: "액티비티 ID", 
	     field: "activityId",
	     flex: 1, // 약 10%
		 cellStyle: () => ({ display: 'flex', justifyContent: 'center' }),
	   }, 

	   { 
	     headerName: "액티비티 명", 
	     field: "activityName",
	     flex: 2.5, // 약 25% (가장 넓게)
	     editable: true,
	     cellStyle: p => ({
	       backgroundColor: p.data?._editedFields?.activityName ? "#FFF3BF" : "#FFF9DB"
	     })
	   }, 
	   { 
	     headerName: "작업 결과물", 
	     field: "outputName",
	     flex: 2.5, // 약 25%
	     editable: true,
	     cellStyle: p => ({
	       backgroundColor: p.data?._editedFields?.outputName ? "#FFF3BF" : "#FFF9DB"
	     })
	   }, 
	   { 
	     headerName: "WBS 날짜", 
	     field: "activityDate", 
	     flex: 1.5,
	     editable: true,
	     cellEditor: 'agDateCellEditor',
	     
	     // [수정] 화면에 보여질 때: 데이터가 Date 객체든 문자열이든 YYYY-MM-DD 형식으로 표시
	     valueFormatter: params => {
	       if (!params.value) return '';
	       const date = new Date(params.value);
	       if (isNaN(date.getTime())) return params.value; // 변환 실패 시 원본 표시
	       const year = date.getFullYear();
	       const month = String(date.getMonth() + 1).padStart(2, '0');
	       const day = String(date.getDate()).padStart(2, '0');
	       return `${year}-${month}-${day}`;
	     },

	     valueGetter: params => {
	       const val = params.data?.activityDate;
	       return val ? new Date(val) : null;
	     },

	     // 저장할 때는 다시 'YYYY-MM-DD' 문자열로 변환하여 data에 저장
	     valueSetter: params => {
	   	const dateObj = params.newValue;
	   	if (params.data && dateObj instanceof Date && !isNaN(dateObj.getTime())) { // params.data 체크 추가
	   	  const year = dateObj.getFullYear();
	   	  const month = String(dateObj.getMonth() + 1).padStart(2, '0');
	   	  const day = String(dateObj.getDate()).padStart(2, '0');
	   	  const newDateStr = `${year}-${month}-${day}`;

	   	  if (params.data.activityDate !== newDateStr) {
	   	    params.data.activityDate = newDateStr;
	   	    
	   	    if (!params.data._editedFields) params.data._editedFields = {};
	   	    params.data._editedFields.activityDate = true;
	   	    if (params.data._rowState !== "INSERT") params.data._rowState = "UPDATE";
	   	    return true;
	   	  }
	   	}
	   	return false;
	     },

	     cellEditorParams: {
	       min: '2025-01-01',
	       max: '2026-12-31',
	     },
	     cellStyle: p => ({
	       textAlign: "center",
	       backgroundColor: p.data?._editedFields?.activityDate ? "#FFF3BF" : "#FFF9DB"
	     })
	   },
	   {
	     headerName: "목표 수량",
	     field: "targetQty",
	     flex: 1.5, // 약 15%
	     editable: true,
	     cellStyle: p => ({
	       textAlign: "right",
	       backgroundColor: p.data?._editedFields?.targetQty ? "#FFF3BF" : "#FFF9DB"
	     })
	   }, 
	 ], []);


  /* =========================
     Data Load
     ========================= */

  const selectList = () => {
      fetch("/api/wbsSetup/selectCombo", {
        method: "POST", // POST 방식 지정
        headers: {
          "Content-Type": "application/json", // JSON 데이터 전송 시 필수
        },
        // 전송할 데이터가 있다면 JSON.stringify({ key: value }) 형태로 추가
      })
        .then(r => r.json())
        .then((data: SelectBoxData[]) => {
		  const filterDataList: [string, string][] = []; 
          const act = new Map<string, string>();
          const out = new Map<string, string>();
          data.forEach(d => {
			filterDataList.push([d.activityName, d.outputName]);
            act.set(d.activityName, d.activityName);
            out.set(d.outputName, d.outputName);
          });
		  
		  setFilterData(filterDataList);
		  /*
		  act: Map { "설계" => "설계", "구현" => "구현" } (특수한 객체 형태)
		  ...act: "설계", "설계", "구현", "구현" (내용물만 쏙 뽑아서 나열)
		  [...act]: [ ["설계", "설계"], ["구현", "구현"] ] (나열된 내용물을 다시 새로운 배열 담기)
		  */
          setActivities([...act]);
          setOutputs([...out]);
        })
		//.catch(): 앞선 .then() 단계들(네트워크 연결, JSON 변환, 데이터 가공) 중 어느 하나라도 에러가 발생할 경우
        .catch(err => console.error("Select Data Load Error:", err));
    };

	//? (Optional Parameter): 이 함수를 호출할 때 인자를 전달하지 않아도 오류가 나지 않음
	//  any: 어떤 타입의 데이터(객체, 문자열, 숫자 등)든 다 받아들임
	//  SearchParams : 정의한 인터페이스 
	const loadGrid = (params?: SearchParams) => {
	  // 전송할 파라미터 객체 const requestBody =  { activityName, outputName, startDate, endDate } 
	  // 옛날방식으로는 var requestBody = { activityName: activityName, outputName: outputName,  startDate: startDate, endDate: endDate };
	  const requestBody = params ? params : { activityName, outputName, startDate, endDate };
		  
	  fetch("/api/wbsSetup/selectList", {
	    method: "POST",
	    headers: {"Content-Type": "application/json"},
	    body: JSON.stringify(requestBody), // 데이터를 JSON 문자열로 변환하여 전송
	  })
	    .then((r) => r.json())
	    .then((data: RowData[]) => {
		  // .map((d) => ({ ... })): 배열의 모든 요소를 순회하며 새로운 형태의 객체로 변환
		  // 람다식에서 **소괄호 ()로 감싼 중괄호 {}**는 "객체를 즉시 반환(Return)하겠다"는 뜻
	      const initializedData = data.map((d) => ({
			//...d (Spread): 기존 데이터(d)의 모든 속성을 그대로 복사해 옴.
			// {...d}는 얕은 복사를 수행함. 만약 d 안에 또 다른 객체나 배열이 들어있다면 그 참조값까지 복사되므로 원본이 같이 바뀔 위험이 있슴
			/* 옛날 스크립트 방식 
			    activityId: d.activityId,
			    activityName: d.activityName,
			    // ... 모든 필드를 일일이 나열해야 함
			*/
	        ...d,
	        _editedFields: {},
	        _oldValues: { activityDate: d.activityDate, activityName:d.activityName , outputName:d.outputName ,targetQty: d.targetQty },
	        _rowState: "NORMAL" as const,
	      }));
	      setRowData(initializedData);
	    })
	    .catch((err) => console.error("Grid Load Error:", err));
	};
	
	const handleReset = () => {
	  setActivityName(""); 
	  setOutputName("");
	  setStartDate(""); 
	  setEndDate("");
	  loadGrid( {activityName: "",  outputName: "", startDate: "", endDate: ""});
	}
	
	useEffect(() => {
	 selectList();
	}, []);
	 
	useEffect(() => {
	  loadGrid();
	}, []);

	useEffect(() => {
	  // 데이터가 없으면 중단
	  if (filterData.length === 0) return;

	  const filteredOutMap = new Map<string, string>();
	  
	  // 1. 액티비티가 '전체'("")인 경우 처리
	  if (activityName === "") {
	    setOutputName(""); // 작업결과물도 '전체'("")로 선택 변경
	  }

	  // filterData를 순회하며 조건에 맞는 결과물만 추출
	  // filterData.forEach(([act, out]) => { ... }): 배열 구조 분해 할당(Destructuring): [act, out] 처럼 배열 내부의 요소를 바로 변수로 꺼내 쓰는 현대적 문법
	  filterData.forEach(([act, out]) => {
	    // 1. activityName이 '전체'("")거나 현재 행의 액티비티와 일치할 때
	    if (activityName === "" || act === activityName) {
			// filteredOutMap.set(out, out) , Map 객체의 특징인 **"키(Key)의 유일성"**을 이용
			// 똑같은 결과물 이름이 100번 들어와도, Map은 기존에 있던 것을 덮어쓰기 때문에 결과적으로 중복 없는 목록 하나만 남게 됨
	      if (out) filteredOutMap.set(out, out); // 중복 제거하며 Map에 담기
	    }
	  });

	  // 2. 필터링된 결과물로 셀렉트박스 업데이트
	  setOutputs([...filteredOutMap]);
	  
	}, [activityName, filterData]);
  /* =========================
     Grid Events
     ========================= */
  //useCallback은 **함수 자체를 메모리에 저장(Memoization)**하여, 컴포넌트가 리렌더링될 때마다 함수가 새로 생성되는 것을 방지하는 Hook
  // useCallback( (params) => { ... }, [의존성] ), 
  // 첫 번째 인자: 실제 실행될 람다식(화살표 함수), 
  // 두 번째 인자 ([]): 이 배열 안의 값이 바뀔 때만 함수를 새로 만듭니다. 비어있다면 컴포넌트 생명주기 동안 딱 한 번만 생성됨
  const onCellValueChanged = useCallback(
	//파라메터 e , 타입은 CellValueChangedEvent , <RowData> : 이 이벤트는 RowData 형식을 가진 데이터를 다룬다
    (e: CellValueChangedEvent<RowData>) => {
		/*  e 에 들어있는 값
		    e.data: 수정된 행(Row) 전체 데이터 (RowData 형식)
		    e.newValue: 사용자가 방금 입력한 새 값
		    e.oldValue: 수정하기 전의 이전 값
		    e.colDef: 수정된 컬럼(열)의 설정 정보 (필드명 등)
		    e.node: 행의 상태(선택 여부 등)를 제어하는 AG Grid 노드 객체
		*/
	  //keyof : 특정 객체(인터페이스)의 키(Key)들만 뽑아내는 연산자 , 타입스크립트(TypeScript) 고유의 문법
	  /*
		  interface RowData {
		    id: number;
		    userName: string;
		    age: number;
		  }
		  // keyof RowData는 "id" | "userName" | "age" 라는 타입이 됨
	  
	  */
      const field = e.colDef.field as keyof RowData;
      const row = e.data;
      if (!row || !row._oldValues) return;

      if (!row._editedFields) row._editedFields = {};
      
	  //e.oldValue, e.newValue 사용하지 않는 이유는 여러 번 값을 바꿨더라도 "최초의 오리지널 값"과 비교하려고 
	  //e.oldValue, e.newValue 바로 직접 변경값이 있어 여러번 바꿀경우 처음 값을 알지 못함
      const oldValue = row._oldValues[field as keyof typeof row._oldValues];
      const newValue = row[field];

      if (oldValue !== newValue) {
        row._editedFields[field as string] = true;
        if (row._rowState !== "INSERT") row._rowState = "UPDATE";
      }
      
      e.api.refreshCells({ rowNodes: [e.node], force: true });
    },
    []
  );

  /* =========================
     Buttons
     ========================= */
	 const handleAdd = () => {
	   const newRow: RowData = {
	     activityId: "",
	     activityDate: "",
	     activityName: "",
	     outputName: "",
	     targetQty: 0,
	     _rowState: "INSERT",
	     _editedFields: {}
	   };

	   // 1. 데이터 상태 업데이트
	   // 여기서 p는 현재 그리드에 보여지고 있는 [ {id:1, ...}, {id:2, ...} ] 배열.
	   setRowData(p => {
		//...p: 기존 배열(p)의 내용물을 전부 낱개로 펼치고 , newRow: 그 뒤에 새 데이터 한 건을 내려놓은 후 , [ ]: 다시 새 주머니(배열)에 담음
	     const updatedData = [...p, newRow];
		 const api = gridApiRef.current;
	     // 2. 데이터가 렌더링된 후 포커스 이동 (setTimeout 사용)
	     setTimeout(() => {
			// useRef()로 만든 변수의 current 안에 실제 API가 있음, 화면이 다 그려지기 전에는 비어있을수 있으므로 확인
	       if (api) {
	         // 마지막 행의 인덱스 계산
	         const rowIndex = updatedData.length - 1;
	         
	         // 해당 행이 화면에 보이도록 스크롤 이동
	         api.ensureIndexVisible(rowIndex);
	         
	         // 'activityDate' 컬럼으로 포커스 및 편집 모드 시작
	         api.setFocusedCell(rowIndex, 'activityDate');
	         api.startEditingCell({
	           rowIndex: rowIndex,
	           colKey: 'activityDate'
	         });
	       }
	     }, 10);

	     return updatedData;
	   });
	 };


  const handleDelete = () => {
    const api = gridApiRef.current;
    if (!api) return;
    const selectedNodes = api.getSelectedNodes();
    const selectedData = selectedNodes.map(n => n.data!).filter(Boolean);
    
    if (selectedData.length === 0) return alert("삭제할 행을 선택하세요.");

    selectedData.forEach(r => {
      if (r._rowState !== "INSERT") {
        deletedRowsRef.current.push(r);
      }
    });
    
    setRowData(p => p.filter(r => !selectedData.includes(r)));
  };

  const handleSave = async () => { // async 추가
      const api = gridApiRef.current;
      if (!api) return;

      // 1. 현재 편집 중인 셀의 상태를 강제로 커밋(확정)
      api.stopEditing(false); // false는 취소가 아닌 '저장'을 의미

      // 2. DataGrid가 내부 row data를 갱신할 수 있도록 아주 짧은 지연(Tick)을 줍니다.
	  // new Promise(...) Promise 객체라서 await 사용가능
      await new Promise(resolve => setTimeout(resolve, 0));

      const insertList: RowData[] = [];
      const updateList: RowData[] = [];
      const deleteList = deletedRowsRef.current;

      // 이제 갱신된 n.data를 읽어옵니다.
	  // 모든 행(Row)을 하나씩 순회(Loop)하며 특정 작업을 수행하는 함수
      api.forEachNode(n => {
        if (n.data?._rowState === "INSERT") insertList.push(n.data);
        else if (n.data?._rowState === "UPDATE") updateList.push(n.data);
      });
	  
	  if (insertList.length + updateList.length + deleteList.length === 0) {
	    alert("변경 사항이 없습니다.");
	    return;
	  }

	  fetch("/api/wbsSetup/saveList", { // 경로 /api 추가 확인
	    method: "POST",
	    headers: { "Content-Type": "application/json" },
	    body: JSON.stringify({ insertList, updateList, deleteList })
	  }).then(r => {
	    if (r.ok) {
	      alert("저장 완료");
	      deletedRowsRef.current = [];
	      loadGrid();
	    } else {
	      alert("저장 실패");
	    }
	  });
  };

  //리액트(React)에서 화면에 보여줄 내용(JSX)을 반환하는 문장의 시작
  return (  
	//<div className="page-wrap">: 전체 페이지를 감싸는 가장 바깥쪽 주머니
	//HTML의 class 대신 리액트에서는 className을 사용
	//{ : 자바스크립트 코드 사용
	/* 사용례 : 패턴 A: 데이터가 있을 때만 그리드 보여주기 
				{rowData ? (
				  <AgGridReact rowData={rowData} ... />
				) : (
				  <p>데이터를 불러오는 중입니다...</p>
				)}
	         패턴 B: 상단 버튼 바 넣기 
				 <div className="button-group">
				   <button onClick={onAddRow}>추가</button>
				   <button onClick={onSave}>저장</button>
				 </div>
	   */
	<div className="page-wrap">
	  {/* 페이지 타이틀: 이모지를 추가하여 시각적 포인트 부여 */}
	  <div className="page-header">
	    <h1 className="page-title">
	      <span style={{ marginRight: '12px' }}>📋</span>WBS Setup
	    </h1>
	  </div>

	  {showSearch && (
	    <div className="search-box-container">
	      <div className="search-box card-shadow">
	        <div className="search-row">
	          <div className="search-item">
	            <label>액티비티</label>
				{/* 1. 액티비티 선택 박스 
					e.target: 현재 글자를 입력 중인 바로 그 <input> 태그 자체를 가리킵
					e.target.value: 그 입력창에 지금 적혀 있는 실제 글자
					e.type : 발생한 이벤트의 종류입니다. 여기서는 "change" 또는 "input"
					e.timeStamp: 이벤트가 발생한 시각 등....
			    */}
				<select value={activityName} onChange={e => setActivityName(e.target.value)}>
				  <option value="">전체</option>
				  {activities.map(([id, name], i) => (
				    // id가 중복될 가능성이 있다면 `${id}-${i}` 처럼 고유하게 만듭니다.
				    <option key={id || i} value={id}>
				      {name}
				    </option>
				  ))}
				</select>
	          </div>
	          <div className="search-item">
	            <label>작업결과물</label>
				{/* 2. 작업결과물 선택 박스 */}
				<select value={outputName} onChange={e => setOutputName(e.target.value)}>
				  <option value="">전체</option>
				  {outputs.map(([id, name], i) => (
				    <option key={id || i} value={id}>
				      {name}
				    </option>
				  ))}
				</select>
	          </div>
			  
			  <div className="search-item">
			    <label>WBS 날짜</label>
			    <input 
			      type="date" 
			      value={startDate} 
			      onChange={e => setStartDate(e.target.value)} 
			      max={endDate} 
			    />
			    <span className="date-separator">~</span>
			    <input 
			      type="date" 
			      value={endDate} 
			      onChange={e => setEndDate(e.target.value)} 
			      min={startDate} 
			    />
			  </div>


	        </div>

	        <div className="search-bottom-bar">
			<div className="search-actions">
			  <button type="button" className="btn reset" onClick={handleReset}>Reset</button>
			  <button type="button" className="btn search primary" onClick={() => loadGrid()}>Search</button>
			</div>
	        </div>
	      </div>

	      <div className="toggle-btn-wrap">
	        <div className="toggle-btn flat" onClick={() => setShowSearch(false)}>
	          ▲ 검색조건 접기
	        </div>
	      </div>
	    </div>
	  )}

	  {!showSearch && (
	    <div className="toggle-btn only-toggle" onClick={() => setShowSearch(true)}>
	      ▼ 검색조건 펼치기
	    </div>
	  )}

	  <div className="grid-toolbar">
	    <div className="left">
	      <button className="btn add action" onClick={handleAdd}>Add</button>
	      <button className="btn delete action" onClick={handleDelete}>Delete</button>
	    </div>
	    <div className="right">
	      <button className="btn save success" onClick={handleSave}>Save</button>
	    </div>
	  </div>

	  <div className="grid-wrap">
	    <div 
	      className="ag-theme-quartz" 
	      style={{ 
	        height: '500px', 
	        width: '100%',
	        '--ag-header-background-color': '#f8f9fa',
	        '--ag-header-foreground-color': '#333',
	        '--ag-border-color': '#e9ecef',
	        '--ag-font-size': '13px',
	      } as React.CSSProperties} 
	    > 
	      <AgGridReact
	        rowData={rowData}
	        columnDefs={columnDefs}
			defaultColDef={defaultColDef}
	        rowHeight={32} 
	        headerHeight={38} 
	        rowSelection={{ 
	          mode: 'multiRow', 
	          checkboxes: false,
	          headerCheckbox: false
	        }}
	        theme={themeQuartz}
	        onGridReady={p => (gridApiRef.current = p.api)}
	        onCellValueChanged={onCellValueChanged}
	      />
	    </div>
	  </div>
	</div>
  );
}

export default WbsSetup;

// vue-front/src/pages/WbsSetup.vue
<script setup lang="ts">
//script setup은 Vue 3에서 Composition API를 더 쉽고 간결하게 사용하기 위해 도입된 컴포넌트 Syntactic Sugar
//타입스크립트 활성화: 해당 컴포넌트 파일(.vue) 내의 <script> 블록에서 자바스크립트 대신 타입스크립트 문법을 사용할 수 있게 됩니다.
/*
1. 기존 방식 (Options API)
데이터는 data에, 함수는 methods에 따로 나눠서 작성하며 this를 사용해야 합니다. 
vue
<///script>
export default {
  data() {
    return {
      count: 0
    }
  },
  methods: {
    increment() {
      this.count++
    }
  }
}
<////script>

<///template>
  <button @click="increment">수치: {{ count }}</button>
<///template>
------------------------------------------------------------------
2. 최신 방식 (Composition API + TypeScript)
<script setup lang="ts">를 사용하면 코드가 훨씬 간결해집니다. 1.3.10
vue
<script setup lang="ts">
import { ref } from 'vue'

// 1. 반응형 데이터 선언 (ref 사용)
// lang="ts" 덕분에 count가 number 타입임을 자동으로 추론합니다.
const count = ref<number>(0)

// 2. 함수 정의 (this가 필요 없음)
const increment = (): void => {
  count.value++ // ref 데이터를 수정할 땐 .value를 붙입니다.
}
<///script>

<///template>
  <!-- 템플릿에서는 .value 없이 변수명만 써도 됩니다. -->
  <button @click="increment">수치: {{ count }}</button>
<///template>
*/

//Vue 3 Composition API의 핵심 함수
/*
1. 반응형 상태 관리 (ref, reactive)
데이터가 변할 때 화면이 자동으로 업데이트되게 만듭니다.
ref: 단일 값(숫자, 문자열, 불리언)이나 객체를 다룰 때 사용합니다. 스크립트에서는 .value로 접근해야 하지만, 템플릿에서는 생략 가능합니다
reactive: 객체나 배열 같은 참조 타입 전용입니다. .value 없이 직접 속성에 접근할 수 있지만, 구조 분해 할당 시 반응성을 잃어버릴 수 있어 주의가 필요합니다.

2. 파생 데이터 및 감시 (computed, watch)
computed: 기존 데이터를 기반으로 계산된 값을 만듭니다. 의존하는 데이터가 변하지 않으면 다시 계산하지 않고 캐싱된 값을 반환해 성능에 유리합니다.
watch: 특정 데이터가 변경될 때마다 **특정 로직(사이드 이펙트)**을 실행합니다. API 호출이나 데이터 변경에 따른 추가 작업이 필요할 때 적합합니다.

3. 라이프사이클 및 DOM 제어 (onMounted, nextTick)
onMounted: 컴포넌트가 화면에 렌더링(마운트)된 직후 실행됩니다. DOM 요소에 접근하거나 초기 데이터를 불러올 때 사용합니다. Vue.js 공식 문서: Lifecycle Hooks
nextTick: 데이터 변경 후 DOM 업데이트가 완료될 때까지 기다려주는 함수입니다. 화면이 바뀐 직후의 DOM 상태를 확인해야 할 때 유용합니다. Vue.js 공식 문서: nextTick
*/

import { ref, reactive, onMounted, watch, nextTick, computed  } from 'vue';


/*
// AG Grid 기본 구조

<script setup lang="ts">
import { ref } from 'vue';
import { AgGridVue } from 'ag-grid-vue3';

  1. 컬럼 정의
const columnDefs = ref([
  { field: "make", headerName: "제조사" },
  { field: "model", headerName: "모델명" },
  { field: "price", headerName: "가격" }
]);

  2. 로우 데이터
const rowData = ref([
  { make: "Toyota", model: "Celica", price: 35000 },
  { make: "Ford", model: "Mondeo", price: 32000 },
  { make: "Porsche", model: "Boxster", price: 72000 }
]);

  3. 기본 컬럼 설정
const defaultColDef = {
  flex: 1,
  sortable: true,
  filter: true,
};
<//script>

<template>
  <!-- AG Grid 컴포넌트 사용 -->
  <ag-grid-vue
    class="ag-theme-alpine"
    style="height: 400px; width: 600px;"
    :columnDefs="columnDefs"
    :rowData="rowData"
    :defaultColDef="defaultColDef"
  >
  <//ag-grid-vue>
<//template>
*/

import { AgGridVue } from 'ag-grid-vue3';

/*
AG Grid Enterprise나 Community 버전에서 TypeScript를 사용할 때 코드의 안정성을 높여주는 핵심 인터페이스

1. 그리드 초기화 및 제어
GridReadyEvent: 그리드가 로드된 직후 실행되는 @grid-ready 이벤트의 타입입니다.
GridApi: 그리드를 프로그래밍적으로 제어(데이터 필터링, 정렬, 선택 등)하기 위한 API 객체의 타입입니다.
themeQuartz: AG Grid의 최신 Quartz 테마를 적용할 때 사용합니다.

2. 데이터 가공 및 서식 (Column Definition)
컬럼 설정(columnDefs) 내에서 데이터를 어떻게 보여주고 수정할지 정의할 때 사용합니다.
ValueGetterParams: 여러 필드를 합치거나 계산된 값을 보여줄 때 (valueGetter) 사용합니다.
ValueFormatterParams: 화면에 표시되는 텍스트의 포맷(예: 날짜 형식, 천 단위 콤마)을 지정할 때 사용합니다.
ValueSetterParams: 사용자가 셀을 수정했을 때 데이터를 어떻게 저장할지 정의합니다.

3. 이벤트 및 스타일링
CellValueChangedEvent: 셀 값이 바뀌었을 때 발생하는 이벤트 타입으로, DB 저장 로직 등을 연결할 때 유용합니다.
CellClassParams: 특정 조건에 따라 셀의 CSS 클래스를 동적으로 변경할 때 (cellClassRules) 사용합니다.

*/

import { 
  type CellValueChangedEvent, 
  type GridApi, 
  type GridReadyEvent,
  type ValueFormatterParams, 
  type ValueGetterParams, 
  type ValueSetterParams, 
  type CellClassParams , 
  themeQuartz 
} from 'ag-grid-community';



// --- Types ---

//AG Grid 컴포넌트와 ref에 이 타입을 주입하면, 데이터 구조가 틀렸을 때 에러를 잡아줍니다.
/*
// 1. 데이터 구조 정의
interface RowData {
  id: number;
  name: string;
  price: number;
  category: 'Electronics' | 'Food' | 'Books'; // 유니온 타입으로 제한 가능
  updatedAt?: string; // 선택적 필드
}

// 2. ref에 타입 적용
const rowData = ref<RowData[]>([
  { id: 1, name: 'MacBook', price: 2500000, category: 'Electronics' },
  { id: 2, name: 'Apple', price: 1500, category: 'Food' }
]);

// 3. GridApi에도 타입 적용 (매우 유용!)
const gridApi = ref<GridApi<RowData>>();

*/
/* 

참조 : typeScript에서 제공하는 유틸리티 타입(Utility Types)
     자바스크립트 객체사용과 같으나 개발시 규칙을 넣음
 
   1. Partial<RowData> (부분 집합)
     의미: RowData 인터페이스의 모든 속성을 선택 사항(Optional, ?)으로 만듭니다.
     왜 쓰나?: _oldValues에 원본 데이터를 다 담지 않고, 수정된 것만 골라서 백업하거나 일부만 저장하고 싶을 때 유용
   2. Record<string, boolean> (지도/사전 구조)
	 의미: Key의 타입은 string이고, Value의 타입은 boolean인 객체를 정의합니다.
	 왜 쓰나요?: 어떤 필드가 수정되었는지 true/false로 기록하는 체크리스트 역할을 하기 위해서입니다.
	 
   3. 차이점
   Partial<RowData>: RowData 인터페이스에 이미 선언된 이름(activityId 등)만 키로 쓸 수 있습니다.	 
   Record<string, boolean>: 선언되지 않은 새로운 문자열도 키로 마음대로 쓸 수 있습니다
   
   // 전체 설명
   
   1. Partial<T> (전부 선택 사항으로!)
   기능: 모든 속성을 ? (옵셔널)로 바꿉니다.
   언제 쓰나?: 데이터의 일부만 수정(Update)하거나, 임시 저장할 때 씁니다.
   예시: Partial<RowData>는 RowData의 필드가 10개라도 1개만 있어도 통과!
   2. Required<T> (무조건 다 넣어!)
   기능: Partial과 반대입니다. 모든 속성을 필수값으로 바꿉니다.
   언제 쓰나?: 옵셔널 필드가 많은 인터페이스를 가져와서, "이 로직에서는 반드시 모든 값이 다 있어야 해"라고 강제할 때 씁니다.
   3. Pick<T, Keys> (필요한 것만 쏙쏙!)
   기능: 특정 타입에서 원하는 키만 골라서 타입을 만듭니다.
   예시: Pick<RowData, 'activityId' | 'activityName'>
   activityId와 activityName만 가진 새로운 타입이 탄생합니다.
   4. Omit<T, Keys> (필요 없는 것만 빼고!)
   기능: Pick과 반대입니다. 특정 키만 제외하고 나머지를 다 가져옵니다.
   언제 쓰나?: 보통 DB의 id나 createdAt처럼 사용자가 입력하지 않아도 되는 필드만 싹 빼고 싶을 때 씁니다.
   예시: Omit<RowData, 'activityId'> (ID만 빼고 나머지 다!)
   5. Record<Keys, Type> (지도/사전 만들기)
   기능: 앞서 설명해 드린 대로, [키 이름의 타입]과 [값의 타입]을 정해서 객체 구조를 만듭니다.
   예시: Record<string, number> (키는 문자열, 값은 숫자만 들어오는 사전)
*/
interface RowData {
  activityId: string;
  activityDate: string;
  activityName: string;
  outputName: string;
  targetQty: number;
  _rowState?: "NORMAL" | "INSERT" | "UPDATE";
  _oldValues?: Partial<RowData>;
  _editedFields?: Record<string, boolean>;
}

interface SearchParams {
  activityName: string;
  outputName: string;
  startDate: string;
  endDate: string;
}

// --- State ---
/*
 const gridApi : 상수 선언: 참조 자체는 변하지 않음을 의미합니다. 하지만 내부의 value는 바뀔 수 있습니다.
 ref< ... > (반응형 래퍼) : 역할: Vue가 추적하는 반응형 컨테이너입니다. 값이 바뀌면 이 객체를 관찰하던 UI가 자동으로 업데이트됩니다
 // ref가 없는 변수는 자바에서 Getter/Setter가 없는 private 필드와 같습니다. 외부(HTML 템플릿)에서 이 값이 변했는지 알 방법이 없습니다.
 // ref가 없으면 v-model이나 {{ activityName }} 같은 Vue의 핵심 기능을 사용할 수 없게 됩니다
 // <!-- 1. v-model 사용 -->
     <input v-model="activityName" //>
    <!-- 2. 풀어서 쓰기 (자바의 Getter + EventListener 구조) -->
     <input 
       :value="activityName" 
       @input="activityName = $event.target.value" 
     //>
   예시
   <script setup lang="ts"//>
   import { ref } from 'vue';

   const activityName = ref(""); // 자바의 private String activityName = "";
   <//script>

   <template>
     <div>
       <!-- 사용자가 '축구'라고 치면 activityName.value는 즉시 '축구'가 됨 -->
       <input type="text" v-model="activityName" placeholder="활동명 검색" />
       
       <p>실시간 검색어: {{ activityName }}</p>
     </div>
   <//template>
	 
   참조 {{ ... }}
   
   자동 언래핑(Unwrapping): 스크립트에서는 activityName.value라고 써야 하지만, 이 중괄호 안에서는 Vue가 알아서 .value를 꺼내서 보여줍니다. 그냥 변수명만 쓰면 됩니다.
   반응성 연결: 만약 사용자가 v-model로 입력창에 글자를 치면, activityName 값이 바뀌고, 그 결과 {{ activityName }}이 적힌 화면의 글자도 실시간으로 바뀝니다.

   
 GridApi<RowData>: AG Grid의 컨트롤러 타입입니다. 
                  제네릭 <RowData>를 한 번 더 사용하여 "이 API가 다루는 행 데이터의 구조는 RowData 인터페이스를 따른다"는 것을 명시합니다. 
				  (자바의 List<MemberDTO>와 같은 계층적 제네릭)
 (null) (초기값) : 괄호 안의 값은 gridApi.value의 초기값입니다. 처음에는 그리드 객체가 없으므로 null로 시작합니다.

*/
const gridApi = ref<GridApi<RowData> | null>(null);
	
//AG Grid에 뿌려줄 실제 데이터 리스트를 정의하는 부분입니다. 자바 개발자에게 익숙한 **List<RowData>** 를 Vue의 반응형 시스템으로 감싼 형태
const rowData = ref<RowData[]>([]);
	
//boolean 필드를 Vue의 반응형 상태(State)로 선언
const showSearch = ref(true);

// Search Filters
//자바의 String activityName = ""; 필드를 Vue의 반응형 상태(State)로 선언한 것
const activityName = ref("");
const outputName = ref("");
const startDate = ref("");
const endDate = ref("");

// Combo Lists
const activities = ref<[string, string][]>([]); 
const outputs = ref<[string, string][]>([]);
const filterData = ref<[string, string][]>([]);
const deletedRows = ref<RowData[]>([]);

// --- Grid Config ---
//computed라는 Vue의 반응형 계산된 속성을 사용하여 AG Grid의 컬럼 정의(columnDefs)를 선언한 것
//의존하는 필드가 바뀔 때만 다시 계산(Caching)되는 Getter 메서드
// computed(() => [...]) 안에 있는 로직을 실행해서 결과값을 columnDefs.value에 담아라. 그런데 만약 참조하는 변수가 변하면 자동으로 다시 실행해라."
// computed는 계산 로직이 포함된 Getter 라면 ref 는  일반 Field (변수) 라고 생각하면 됨
const columnDefs = computed(() => [
  {
    headerName: 'No',
    valueGetter: "node.rowIndex + 1",
    width: 60,
    minWidth: 60,
    maxWidth: 70,
	filter: false, 
    cellStyle: { textAlign: 'center', color: '#888' },
  },
  {
    headerName: 'Sel',
    width: 60,
    minWidth: 60,
    maxWidth: 70,
    checkboxSelection: true,
    headerCheckboxSelection: true,
    pinned: 'left',
    cellStyle: { display: 'flex', textAlign: 'center' },
    headerClass: 'ag-header-cell-center',
  },
  {
    headerName: "액티비티 ID",
    field: "activityId",
    flex: 1,
    cellStyle: { display: 'flex', textAlign: 'center' },
  },
  {
    headerName: "액티비티 명",
    field: "activityName",
    flex: 2.5,
    editable: true,
    // [중요] 배경색 로직 적용
	cellStyle: (params: CellClassParams ) => ({
	  backgroundColor: params.data?._editedFields?.activityName ? "#FFF3BF" : "#FFF9DB"
	})
  },
  {
    headerName: "작업 결과물",
    field: "outputName",
    flex: 2.5,
    editable: true,
    cellStyle: (params: CellClassParams ) => ({
      backgroundColor: params.data?._editedFields?.outputName ? "#FFF3BF" : "#FFF9DB"
    })
  },
  {
      headerName: "WBS 날짜",
      field: "activityDate",
      flex: 1.5,
      editable: true,
      cellEditor: 'agDateCellEditor',

      // 1. 화면 표시 형식 (문자열 반환)
      valueFormatter: (params: ValueFormatterParams) => {
        if (!params.value) return '';
        const date = new Date(params.value);
        if (isNaN(date.getTime())) return params.value;
        return date.toISOString().split('T')[0];
      },

      // 2. 에디터(날짜 선택기)에 전달할 값 (Date 객체 반환)
      valueGetter: (params: ValueGetterParams) => {
        const val = params.data?.activityDate;
        return val ? new Date(val) : null;
      },

      // 3. 저장 시 로직 (데이터 변경 및 플래그 설정)
	  valueSetter: (params: ValueSetterParams) => {
	    const dateObj = params.newValue;
	    
	    // 1. 선택된 값이 유효한 Date 객체인지 확인
	    if (params.data && dateObj instanceof Date && !isNaN(dateObj.getTime())) {
	      // YYYY-MM-DD 형식으로 변환
	      const year = dateObj.getFullYear();
	      const month = String(dateObj.getMonth() + 1).padStart(2, '0');
	      const day = String(dateObj.getDate()).padStart(2, '0');
	      const newDateStr = `${year}-${month}-${day}`;

	      // 2. 값이 실제로 변했을 때만 처리
	      if (params.data.activityDate !== newDateStr) {
	        params.data.activityDate = newDateStr; // 데이터 업데이트
	        
	        // 상태 플래그 설정
	        if (!params.data._editedFields) params.data._editedFields = {};
	        params.data._editedFields.activityDate = true;
	        
	        if (params.data._rowState !== "INSERT") {
	          params.data._rowState = "UPDATE";
	        }
	        
	        return true; // 중요: true를 반환해야 AG Grid가 변경을 확정함
	      }
	    }
	    return false; // 변경 실패 시 false 반환
	  },

      // 4. 에디터 설정
      cellEditorParams: {
        min: '2025-01-01',
        max: '2026-12-31',
      },

      // 5. 조건부 스타일 (배경색)
      cellStyle: (params: CellClassParams) => ({
        textAlign: "center",
        backgroundColor: params.data?._editedFields?.activityDate ? "#FFF3BF" : "#FFF9DB"
      })
    },
  {
    headerName: "목표 수량",
    field: "targetQty",
    flex: 1.5,
    editable: true,
    cellStyle: params => ({
      textAlign: "right",
      backgroundColor: params.data?._editedFields?.targetQty ? "#FFF3BF" : "#FFF9DB"
    })
  },
]);

const defaultColDef = {
  flex: 1,
  minWidth: 100,
  resizable: true,
  sortable: true,
  filter: false,
};

// --- Methods ---

const selectCombo = () => {
  fetch("/api/wbsSetup/selectCombo", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
  })
    .then(r => r.json())
	// any[] : 어떤 타입(any)이든 상관없이 요소로 가질 수 있는 배열
    .then((data: SearchParams[]) => { 
      const filterDataList: [string, string][] = [];
      const act = new Map<string, string>();
      const out = new Map<string, string>();

      data.forEach(d => {
        filterDataList.push([d.activityName, d.outputName]);
        // Map을 사용하여 중복 제거
        act.set(d.activityName, d.activityName);
        out.set(d.outputName, d.outputName);
      });

      // 3. 값 할당 (Vue 3의 ref로 선언된 반응형 변수에 값을 넣을 때 .value를 사용)
      filterData.value = filterDataList;
      activities.value = [...act];
      outputs.value = [...out];
    })
    .catch(err => {
      console.error("Select Data Load Error:", err);
    });
};


const selectList = () => {
  // 1. 전송할 파라미터 구성 (Vue ref이므로 .value 사용)
  const requestBody = { 
    activityName: activityName.value, 
    outputName: outputName.value, 
    startDate: startDate.value, 
    endDate: endDate.value 
  };

  fetch("/api/wbsSetup/selectList", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(requestBody),
  })
  .then((res) => {
    if (!res.ok) throw new Error(`서버 에러: ${res.status}`);
    return res.json();
  })
  
  //  (data: RowData[]) => {
  /**
   * 화살표 함수(Arrow Function)의 시작입니다
   * data라는 이름의 파라미터를 받습니다.
   * RowData[]는 data가 RowData라는 타입을 가진 객체들의 배열임을 명시합니다.
   */	
  .then((data: RowData[]) => {
	/*rowData.value = data.map((d) => ({
	* rowData.value: Vue 3의 ref로 선언된 반응형 변수에 값을 넣을 때 .value를 사용합니다.
	* data.map(...): 배열의 내장 메서드로, 기존 배열을 순회하며 새로운 형태의 배열을 만들어 반환합니다.
	* (d) => ({: 각 항목(d)을 순회하며 객체({})를 즉시 반환(Implicit Return)하겠다는 뜻
	* 괄호 ( 가 없으면 함수의 몸체 { 로 인식되기 때문에 객체 반환 시 필수입니다.
	*/	
    rowData.value = data.map((d) => ({
      ...d,
      _editedFields: {},
      _oldValues: { 
        activityDate: d.activityDate, 
        activityName: d.activityName, 
        outputName: d.outputName, 
        targetQty: d.targetQty 
      },
      _rowState: "NORMAL", // Vue에서는 'as const' 없이 문자열로 할당 가능 (인터페이스 타입에 따라 조절)
    }));
  })
  .catch((err) => {
    console.error("Grid Load Error:", err);
  });
};

const handleReset = () => {
  activityName.value = "";
  outputName.value = "";
  startDate.value = "";
  endDate.value = "";
  selectList();
};

const handleAdd = () => {
  const newRow: RowData = {
    activityId: "",
    activityDate: "",
    activityName: "",
    outputName: "",
    targetQty: 0,
    _rowState: "INSERT",
    _editedFields: {}
  };
  
  // 1. Vue의 반응형 데이터(rowData)에 먼저 추가 (중요!)
  // ...rowData :  rowData.push(newRow) 를 안쓰고 
  // 새로운 배열을 대입(=)하는 방식은 데이터가 아예 교체되었다"고 Vue에게 확실히 신호를 주기 때문에 불변성(Immutability)을 지키는 코딩 패턴에서 선호된다고함
  //
  rowData.value = [...rowData.value, newRow];
  
  // 2. 그 다음 AG Grid API를 통해 화면에 반영하고 포커스 처리
  // (rowData.value를 통째로 바꾸면 그리드가 리렌더링되므로, 
  //  안전하게 순차적으로 처리하거나 혹은 데이터 바인딩 방식에 맞춰 수정이 필요합니다.)

  setTimeout(() => {
    if (gridApi.value) {
      const lastIndex = rowData.value.length - 1;
      
	  //스크롤이동
      gridApi.value.ensureIndexVisible(lastIndex);
	  //포커스 이동
      gridApi.value.setFocusedCell(lastIndex, 'activityName');
	  //편집 모드(입력창)를 즉시 활성화
      gridApi.value.startEditingCell({ rowIndex: lastIndex, colKey: 'activityName' });
    }
  }, 50);
};

const handleDelete = () => {
  if (!gridApi.value) return;
  
  //현재 선택 상태인 행들의 '노드(Node) 객체'들을 배열로 반환
  //노드(Node)란?: 단순한 데이터(data)뿐만 아니라, 그 행이 몇 번째인지(rowIndex), 선택되었는지(selected) 등의 상태 정보까지 포함된 AG-Grid 전용 객체
  const selectedNodes = gridApi.value.getSelectedNodes();
  
  /*
  실제 데이터(data)만 쏙 뽑아내고, 빈 값(null/undefined)을 걸러냄
  /**
   * .map(n => n.data): selectedNodes는 그리드 정보가 담긴 '노드' 뭉치입니다. 여기서 우리가 필요한 순수 데이터 객체(d.data)만 추출해서 새로운 배열을 만듭니다.
   * .filter(...): 추출된 데이터 중 혹시나 있을지 모를 null이나 undefined를 제거하여 안전한 배열을 만듭니다.
   * (d): d is RowData => !!d: 타입 가드(Type Guard)라는 고급 TypeScript 문법입니다.
   * !!d: 데이터가 존재하면 true, 없으면 false로 취급합니다.
   * d is RowData: 이 필터를 통과한 데이터(d)는 확실히 RowData 타입이라고 컴파일러에게 확신을 줍니다.
  */
  const selectedData = selectedNodes.map(n => n.data).filter((d): d is RowData => !!d);

  if (selectedData.length === 0) return alert("삭제할 행을 선택하세요.");

  selectedData.forEach(r => {
    if (r._rowState !== "INSERT") deletedRows.value.push(r);
  });

  rowData.value = rowData.value.filter(r => !selectedData.includes(r));
};

/*
1. 문법 분석
const onCellValueChanged: 함수 이름을 정의합니다. AG-Grid에서 관습적으로 사용하는 이벤트 이름입니다.
e: 이벤트 객체(Event)입니다. 누가, 어떤 줄의, 어떤 칸을, 원래 뭐였는데, 무엇으로 바꿨는지에 대한 모든 정보가 이 e 안에 담겨 있습니다.
: CellValueChangedEvent<RowData>: TypeScript 문법입니다.
e가 단순한 객체가 아니라, **"셀 값이 변경된 이벤트"**라는 구체적인 타입임을 명시합니다.
<RowData>는 이 그리드가 다루는 데이터가 우리가 만든 RowData 규격임을 알려주어, e.data.activityName 같은 자동 완성을 가능하게 합니다.
2. e 객체에서 자주 쓰는 정보들
함수 내부에서 보통 이런 값들을 꺼내 씁니다:
e.data: 수정된 행 전체 데이터 (바뀐 후의 값 포함)
e.oldValue: 수정하기 전의 원래 값
e.newValue: 사용자가 새로 입력한 값
e.column.getColId(): 어떤 컬럼(열)이 수정되었는지 ID 확인

*/

const onCellValueChanged = (e: CellValueChangedEvent<RowData>) => {
  const row = e.data;
  if (!row) return;

  /*
  e.colDef.field: 그리드 설정(columnDefs)에서 정의했던 필드명(예: 'activityName', 'targetQty')을 가져옵니다.
  as (Type Assertion): 타입스크립트에게 **"이 문자열은 그냥 아무 글자가 아니라, RowData 안에 있는 키(Key) 중 하나가 확실해!"**라고 강하게 말하는 것입니다.
  */
  const field = e.colDef.field as keyof RowData;
  const oldValue = e.oldValue;
  const newValue = e.newValue;

  // 1. 값이 변하지 않았다면 아무것도 하지 않음
  if (oldValue === newValue) return;

  // 2. 편집된 필드 기록 객체가 없다면 초기화
  if (!row._editedFields) row._editedFields = {};
  row._editedFields[field as string] = true;

  // 3. 행 상태 변경 (INSERT 상태가 아닐 때만 UPDATE로 변경)
  if (row._rowState !== "INSERT") {
    row._rowState = "UPDATE";
  }

  // 4. AG Grid 화면 강제 갱신 (스타일이나 아이콘 변경 반영용)
  e.api.refreshCells({ rowNodes: [e.node], force: true });
};

const handleSave = async () => {
  if (!gridApi.value) return;
  gridApi.value.stopEditing(false);
  
  //await new Promise(resolve => setTimeout(resolve, 0));
  //데이터를 바꾼 후, Vue가 화면(DOM)을 실제로 다 그릴 때까지 기다려라"라고 명령하는 함수
  await nextTick();
  
  const insertList = rowData.value.filter(r => r._rowState === "INSERT");
  const updateList = rowData.value.filter(r => r._rowState === "UPDATE");
  const deleteList = deletedRows.value;

  if (insertList.length + updateList.length + deleteList.length === 0) {
    return alert("변경 사항이 없습니다.");
  }

  fetch("/api/wbsSetup/saveList", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ insertList, updateList, deleteList })
  }).then(r => {
    if (r.ok) {
      alert("저장 완료");
      deletedRows.value = [];
      selectList();
    } else {
      alert("저장 실패");
    }
  });
};


const onGridReady = (params: GridReadyEvent) => {
  gridApi.value = params.api;
};

// --- Watchers ---
//이 코드는 **"활동명(activityName) 변수가 바뀔 때마다 감시(Watch)하고 있다가, 값이 변하는 순간 특정 동작을 실행해라"**라는 뜻의 Vue 3 반응형 감시자
watch(activityName, (newVal) => {
  if (newVal === "") outputName.value = "";
  
  const filteredOutMap = new Map<string, string>();
  //([act, out]) 부분은 자바스크립트의 구조 분해 할당(Destructuring) 문법
  /*
  filterData.value: Vue의 ref로 선언된 배열 데이터에 접근합니다.
  .forEach(...): 배열의 모든 요소를 순회하며 함수를 실행합니다.
  ([act, out]) => {:
  배열의 각 항목이 또 다른 배열(예: ['코딩', '결과물.zip']) 형태일 때 사용합니다.
  첫 번째 값을 act라는 변수에, 두 번째 값을 out이라는 변수에 즉시 대입해서 함수 안에서 바로 쓸 수 있게 해줍니다.
  */
  filterData.value.forEach(([act, out]) => {
    if (newVal === "" || act === newVal) {
      if (out) filteredOutMap.set(out, out);
    }
  });
  outputs.value = [...filteredOutMap.entries()];
});

onMounted(() => {
  selectCombo(); // 콤보 데이터 로드 호출
  selectList();    // 초기 그리드 데이터 로드
});

</script>

<template>
  <div class="page-wrap">
    <div class="page-header">
      <h1 class="page-title">
        <span style="margin-right: 12px">📋</span>WBS Setup
      </h1>
    </div>

    <!-- Search Box -->
    <div v-if="showSearch" class="search-box-container">
      <div class="search-box card-shadow">
        <div class="search-row">
          <div class="search-item">
            <label>액티비티</label>
            <select v-model="activityName">
              <option value="">전체</option>
              <option v-for="[id, name] in activities" :key="id" :value="id">{{ name }}</option>
            </select>
          </div>
          <div class="search-item">
            <label>작업결과물</label>
            <select v-model="outputName">
              <option value="">전체</option>
              <option v-for="[id, name] in outputs" :key="id" :value="id">{{ name }}</option>
            </select>
          </div>
          <div class="search-item">
            <label>WBS 날짜</label>
            <input type="date" v-model="startDate" :max="endDate" />
            <span class="date-separator">~</span>
            <input type="date" v-model="endDate" :min="startDate" />
          </div>
        </div>
        <div class="search-bottom-bar">
          <div class="search-actions">
            <button @click="handleReset" class="btn reset">Reset</button>
            <button @click="selectList()" class="btn search primary">Search</button>
          </div>
        </div>
      </div>
      <div class="toggle-btn-wrap">
        <div class="toggle-btn flat" @click="showSearch = false">▲ 검색조건 접기</div>
      </div>
    </div>

    <div v-else class="toggle-btn only-toggle" @click="showSearch = true">▼ 검색조건 펼치기</div>

    <!-- Grid Toolbar -->
    <div class="grid-toolbar">
      <div class="left">
        <button @click="handleAdd" class="btn add action">Add</button>
        <button @click="handleDelete" class="btn delete action">Delete</button>
      </div>
      <div class="right">
        <button @click="handleSave" class="btn save success">Save</button>
      </div>
    </div>

    <!-- AG Grid -->
    <div class="grid-wrap">
      <ag-grid-vue
        class="ag-theme-quartz"
        style="height: 500px; width: 100%;"
        :rowData="rowData"
        :columnDefs="columnDefs"
        :defaultColDef="defaultColDef"
        :rowHeight="32"
        :headerHeight="38"
        :rowSelection="{ mode: 'multiRow', 
			          checkboxes: false,
			          headerCheckbox: false}"
        :theme="themeQuartz"
        @grid-ready="onGridReady"
        @cell-value-changed="onCellValueChanged"
      />
    </div>
  </div>
</template>
