// vue-front/src/components/Sidebar.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { useRouter, useRoute } from 'vue-router'; 
import type { Menu } from '../menu';
import '../css/layout.css';
// 1. 타입을 인터페이스로 정의
interface SidebarProps {
  parentMenuName: string;
  level2Menus: Menu[];
  activeLevel2: Menu | null;
}

// 2. 정의한 인터페이스를 Props에 적용 (한 번만 선언해야 합니다)
const props = defineProps<SidebarProps>();

// 2. Emit 정의 (상태 변경을 부모에게 알림)
const emit = defineEmits<{
  (e: 'setActiveLevel2', menu: Menu | null): void;
}>();

const router = useRouter();
const route = useRoute(); // 현재 경로 정보 객체

// 3. State 정의 (리액트의 useState 역할)
const open = ref(true);

// 4. 메뉴 클릭 핸들러
const sideMenuClick = (menu: Menu) => {
  emit('setActiveLevel2', menu);
  if (menu.menuUrl) {
    router.push(menu.menuUrl);
  }
};

// 5. Watcher (리액트의 useEffect 역할)
// activeLevel2가 변경될 때마다 실행되며, 현재 경로와 다를 경우 자동으로 이동
watch(
  () => props.activeLevel2,
  (newActive) => {
    if (newActive && newActive.menuUrl) {
      // route.path가 현재 브라우저 주소입니다.
      if (route.path !== newActive.menuUrl) {
        router.push(newActive.menuUrl);
      }
    }
  },
  { immediate: true } // 컴포넌트가 처음 로드될 때도 실행 (useEffect의 마운트 시점과 동일)
);
</script>

<template>
  <div id="sidebar">
    <div class="sidebar-group">
      <!-- 메뉴 열기/닫기 토글 -->
      <div 
        class="sidebar-title" 
        @click="open = !open" 
        style="cursor: pointer"
      >
        📁 {{ parentMenuName }} {{ open ? "▾" : "▸" }}
      </div>

      <!-- v-if를 사용하여 open일 때만 렌더링 -->
      <div 
        v-if="open" 
        class="sidebar-list" 
        :class="{ active: open }"
      >
        <div
          v-for="menu in level2Menus"
          :key="menu.menuId"
          class="sidebar-item"
          :class="{ active: activeLevel2?.menuId === menu.menuId }"
          @click="sideMenuClick(menu)"
          style="cursor: pointer"
        >
          📄 {{ menu.menuName }}
        </div>
      </div>
    </div>
  </div>
</template>

// react-front/src/components/Sidebar.tsx
import { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { type Menu } from "../menu";

interface Props {
  parentMenuName: string;
  level2Menus: Menu[];
  selectSubMenus: (menus: Menu[]) => void;
  activeLevel2: Menu | null;
  setActiveLevel2: (menu: Menu | null) => void; 
}

export default function Sidebar({
  parentMenuName,
  level2Menus,
  activeLevel2,
  setActiveLevel2,
}: Props) {
	
  const navigate = useNavigate();
  const location = useLocation(); // 현재 URL 경로를 가져옴
	
  const [open, setOpen] = useState(true);

  const sideMeneClick = (menu: Menu) => {
    setActiveLevel2(menu);
    if (menu.menuUrl) navigate(menu.menuUrl);
  };
  
  // activeLevel2가 변경될 때마다 실행 (자동 이동 포함)
  useEffect(() => {
    // 1. 선택된 메뉴가 있고 URL이 있는지 확인
    if (activeLevel2 && activeLevel2.menuUrl) {
      // 2. 핵심: 현재 브라우저 주소와 이동할 메뉴의 주소가 다를 때만 navigate!
      // 이렇게 하면 App에서 첫 번째 메뉴를 세팅했을 때도 자동으로 이동합니다.
      if (location.pathname !== activeLevel2.menuUrl) {
        navigate(activeLevel2.menuUrl);
      }
    }
  }, [activeLevel2, navigate, location.pathname]);
  
  return (
    <div id="sidebar">
      <div className="sidebar-group">
        <div className="sidebar-title" onClick={() => setOpen(!open)} style={{ cursor: 'pointer' }}>
          📁 {parentMenuName} {open ? "▾" : "▸"}
        </div>
        {/* open이 true일 때만 div를 렌더링하고, 클래스명에 active를 추가합니다 */}
        {open && (
          <div className={`sidebar-list ${open ? "active" : ""}`}>
            {level2Menus.map(menu => (
              <div
                key={menu.menuId}
                className={`sidebar-item ${activeLevel2?.menuId === menu.menuId ? "active" : ""}`}
                onClick={() => sideMeneClick(menu)}
                style={{ cursor: 'pointer' }}
              >
                📄 {menu.menuName}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );

}
